%% [mṛg, a], [a, ṅkaḥ], [mṛg, ā, ṅkaḥ]
%% [tath, ā], [a, pi], [tath, ā, pi]
%% [tav, a], [ā, śā],  [tav, ā, śā]
%% [sīt, ā], [ā, gatā],  [sīt, ā, gatā]
%% [vidy, ā], [, ālayaḥ], [vidy, ā, layaḥ]
%% [mun, i], [i, ndraḥ], [mun, ī, draḥ]
%% [har, i], [īśaḥ], [har, ī, śaḥ]
%% [lakṣm, ī], [ī, śvaraḥ], [lakṣm, ī, śvaraḥ]
%% [bhān, u], [u, dayaḥ], [bhān, ū, dayaḥ]
%% [sindh, ū], [ū, rmiḥ ], [sindh, ū, rmiḥ]
%% [bh, ū], [u, dhvarm], [bh, ū, rdhvam]
%% [s, u], [u, ktiḥ ], [s, ū, ktiḥ]
%% [māt, ṛ], [ṛ, ṇam], [māt, ṝ, ṇam]
%% [pit, ṛ], [ṛ, ddhiḥ], [pit, ṝ, rddhiḥ]

%% [nar, a], [i, ndraḥ], [nar, e, ndraḥ]
%% [mah, ā], [i, ndraḥ], [mah, e, ndraḥ]
%% [mah, ā], [ī, śaḥ],  [mah, e, śaḥ]
%% [nar, a], [u, ttamaḥ], [nar, o, ttamaḥ]
%% [gaṅg, ā], [u, dakam], [gaṅg, o, dakam]
%% [kṛṣṇ, a], [ṛ, ddhiḥ], [kṛṣṇ, ar, ddhiḥ]
%% [mah, ā], [ṛ, ṣiḥ], [mah, ar, ṣiḥ]
%% [tav, a], [ḷ, kāraḥ], [tav, al, kāraḥ]
%% [māl, ā], [ḷ, kāraḥ], [māl, al, kāraḥ]

%% [kṛṣṇ, a], [e, katvam], [kṛṣṇ, ai, katvam]
%% [dev, a], [a, iśvaryam], [dev, ai, śvaryam]
%% [tath, ā], [e, va], [tath, ai, va]
%% [mah, ā], [a, irāvataḥ], [mah, ai, rāvataḥ]
%% [jal, a], [o, ghaḥ], [jal, au, ghaḥ]
%% [tav, a], [a, udāryam], [tav, au, dāryam]
%% [mah, ā], [o, ghaḥ], [mah, au, ghaḥ]
%% [mah, ā], [a, udāryam], [mah, au, dāryam]
%% [pr, a], [ṛ, cchati], [pr, ār, cchati]
%% [up, a], [ṛ, cchati], [up, ār, cchati]

%% [yad, i], [a, pi], [yad, y, api]
%% [it, i], [ā, di], [it, y, ādiḥ]
%% [nad, ī], [a, sti], [nad, y, asti]
%% [lakṣm, ī], [ā, gacchati], [lakṣm, y, āgacchati]
%% [madh, u], [a, riḥ], [madh, v, ariḥ]
%% [sādh, u], [ā, deśaḥ], [sādh, v, ādeśa]
%% [s, u], [ā, gatama], [s, v, āgatam]
%% [vadh, ū], [ā, deśaḥ], [vadh, v, ādeśaḥ]
%% [cam, ū], [ā, gamanama], [cam, v, āgamanam]
%% [pit, ṛ], [ā, deśaḥ], [pit, r, ādeśaḥ]
%% [māt, ṛ], [ā, jñā], [māt, r, ājñā]
%% [, ḷ], [ā, kṛti], [l, ākṛti, lākṛtiḥ]
%% [, ḷ], [a, kāra], [l, akāraḥ, ]
%% [har, e], [e, ], [har, ay, e]
%% [kav, e], [e, ], [kav, ay, e]
%% [na, i], [a, kaḥ], [n, āy, akaḥ]
%% [ra, i], [o, ḥ], [r, āy, oḥ]
%% [viṣṇ, o], [e, ], [viṣṇ, av, e]
%% [bhān, o], [e, ], [bhān, av, e]
%% [pa, u], [a, kaḥ], [p, āv, akaḥ]
%% [ga, u], [a, u], [g, āv, au]
%% [na, u], [a, m], [n, āv, am]
%% [grām, e], [a, smin], [grām, e', smin]
%% [nagar, e], [a, tra], [nagar, e', tra]
%% [sādh, o], [a, tra],  [sādh, o', tra]
%% [prabh, o], [a, tra], [prabh, o', tra]
%% [har, e], [a, va],  [har, e', va]
%% [viṣṇ, o], [a, va], [viṣṇ, o', 'va]
